### PR TITLE
Trim field names in compiler generated types

### PR DESCRIPTION
**Pull request by marek-safar**
Contributes to #1282

Saves about 10k (uncompressed) for default Blazor template

### CODE REVIEW

**Comment by MichalStrehovsky** [comment]
What does this do to:

```csharp
using System;
using System.Collections.Generic;

var g = new Gen<string>();
var e = g.Enumerate(1, 2).GetEnumerator();
e.MoveNext();

class Gen<T>
{
    public IEnumerable<int> Enumerate(int x, int y)
    {
        yield return x;
        yield return y;
    }
}
```

I expect this program to be broken with this optimization.

I tried to capture the rules of when and how this can be done safely in https://github.com/mono/linker/issues/1282 (it also covers more cases than just fields on types marked with CompilerGeneratedAttribute).

**Comment by marek-safar** [comment]
Yep, that fails with `System.MissingFieldException` but I think excluding fields with TypeSpec field type should covert that, right?

**Comment by MichalStrehovsky** [comment]
Yes, that would fix that one.

But CompilerGeneratedAttribute is a general purpose attribute that is not specific to stuff generated by e.g. Roslyn. People can just slap it on stuff e.g. generated by source generators or other tools. There's no guarantees that there wouldn't be another assembly trying to access the field through a MemberRef, hitting MissingFieldException again. We need to make sure the field is not accessible from outside the assembly (or that no other assembly accesses it, if we have a global view).

I'm not sure if there's a way to approximate #1282 without actually doing everything in #1282.

**Comment by marek-safar** [comment]
> There's no guarantees that there wouldn't be another assembly trying to access the field through a MemberRef, hitting MissingFieldException again.

Why does MemberRef matter? I thought that if we record all fields used via TypeSpec to require name there should be no MissingFieldException.

**Comment by MichalStrehovsky** [comment]
TypeSpec is only used for generic classes, which is why the above repro program breaks (the yield return state machine is generic).

I meant the general:

## Assembly A

```csharp
[CompilerGenerated]
public class Foo
{
    public int Field;
}
```

## Assembly B

```csharp
Foo.Field = 1234;
```

There's no TypeSpec.

**Pull request closed without merging**
