### PR TITLE
[feature/damAnalyzer] Merge changes from release/6.0.2xx

### PR DESCRIPTION
**Pull request by sbomer**

### CODE REVIEW

**Comment by sbomer** [comment]
The recent changes that run tests with all analyzers enabled are causing https://github.com/dotnet/linker/issues/2308 to show up in more places here. We'll probably want to fix that rather than disabling the failing tests like I did in https://github.com/dotnet/linker/pull/2307.

**Comment by tlakollo** [comment]
> The recent changes that run tests with all analyzers enabled are causing #2308 to show up in more places here. We'll probably want to fix that rather than disabling the failing tests like I did in #2307.

Just to double-check, the RAF analyzer is not running because we didn't pass the MSBuildOptions.EnableSingleFileAnalyzer yet. And the Interop files don't have any errors so I guess is just that some changes in that PR make exacerbated #2308, right?

**Comment by sbomer** [comment]
That's right - sorry, I meant the changes that run tests with all _trim_ analyzers. Those changes are exacerbating https://github.com/dotnet/linker/issues/2308. For example the failures in the RequiresCapability tests are coming from the DAM analyzer which didn't used to run on that testcase.

**Comment by tlakollo** [comment]
Considering that there is already a PR that has a fix for the spurious IL2082 and that other PRs will fail without the fix 
`Switch to ubuntu 20.04 agents (dotnet#2322)` I think is best to merge this PR and pollute the branch while we merge #2348

**Review by tlakollo — APPROVED** [review]
Looks good to me

**Pull request merged**
