### PR TITLE
Rename AOT property to match msbuild camel case

### PR DESCRIPTION
**Pull request by tlakollo**

### CODE REVIEW

**Review by sbomer — COMMENTED** [review]
What's the reasoning behind the change? We seem to use NativeAOT elsewhere. I personally think EnableAOTAnalyzer reads better and I'd prefer to keep the acronym capitalized.

**Comment by tlakollo** [comment]
I think we should follow a convention if there is any. Although they are examples of using the properties in both ways saw a couple of ARM properties. I think the inclination is to use the camel case in msbuild. They are several examples when using things like ASP.NET, HTTP, SDK, URL, etc.
https://github.com/dotnet/sdk/blob/main/eng/Versions.props#L136-L144
https://github.com/dotnet/sdk/blob/main/src/WebSdk/Package.props#L27-L28

**Comment by agocke** [comment]
It does seem like the MSBuild convention is CamelCase. I'd recommend sticking with MSBuild convention unless we have some other convention to follow

**Review by sbomer — APPROVED** [review]
Thanks for the rationale, makes sense!

**Pull request merged**
