### PR TITLE
Fix lint job in CI

### PR DESCRIPTION
**Pull request by vitek-karas**
It did run linter, but didn't fail if any changes were to be applied, instead it actually applied them (and then dropped). So the job would actually never fail.

### CODE REVIEW

**Review by sbomer — APPROVED** [review]
There are still some formatting failures in test files, otherwise LGTM.

**Comment by vitek-karas** [comment]
This is really weird - I ran it locally to "fix" things, and it didn't do those - but then it fails on them?

**Comment by sbomer** [comment]
Weird... could it be using a different version of dotnet-format locally for some reason? I have hit problems in the past with breaking changes to dotnet-format and IIRC I had to be very careful to make sure it used the right SDK.

**Comment by vitek-karas** [comment]
Honestly - the tool is... confusing.

`dotnet format` may not fix some warnings - and it says so with something like `Unable to apply fixes for <id>`. But it does not show the warnings it wasn't able to fix.
`dotnet format --verify-no-changes` on the other hand shows these warnings.

You can force `dotnet format` to show them as well with `-v d`, but that produces lot of output - mostly useless and the warnings are sort of hidden in the middle.

`dotnet format` does not return error exit code if fails to fix things.

`dotnet format` may say that it failed to fix things, while it actually did fix them (specifically IDE00005 - unused using).

So for now I did this:
* Most of the warnings were unused parameters in tests -> I disabled those in the editorconfig as this is basically expected for tests
* I fixed one warning which made sense
* I modified our `lint` scripts to run the tool twice. First to actually apply formatting and second time with the `--verify-no-change` - this has the effect that it will report unfixed warnings and it will actually fail the command if there are any.

It's not perfect, it takes a while to run (twice) and the output is still unnecessarily long, but at least it works.

**Comment by vitek-karas** [comment]
I filed https://github.com/dotnet/format/issues/1508 to hopefully improve the tool

**Review by marek-safar — APPROVED** [review]

**Pull request merged**
