### PR TITLE
Port Fix for TryResolve scenario

### LINKED ISSUE #2274: Crash in linker building with .NET 6 RC1
Building VSMac with .NET 6 RC1 I get this error:

```
ILLink : error IL1012: IL Linker has encountered an unexpected error. Please report the issue at https://github.com/mono/linker/issues [/Users/lluis/prog/work/vsmac/test/main/src/tools/vstool/vstool.csproj]
  Fatal error in IL Linker
  Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
     at Mono.Linker.CustomAttributeSource.HasAny(ICustomAttributeProvider provider)
     at Mono.Linker.AnnotationStore.GetLinkerAttributes[T](IMemberDefinition member)
     at Mono.Linker.AnnotationStore.TryGetLinkerAttribute[T](IMemberDefinition member, T& attribute)
     at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference, DependencyInfo reason, Nullable`1 origin)
     at Mono.Linker.Steps.MarkStep.MarkField(FieldDefinition field, DependencyInfo& reason)
     at Mono.Linker.Steps.MarkStep.MarkEntireType(TypeDefinition type, DependencyInfo& reason)
     at Mono.Linker.Steps.MarkStep.MarkEntireAssembly(AssemblyDefinition assembly)
     at Mono.Linker.Steps.MarkStep.MarkAssembly(AssemblyDefinition assembly, DependencyInfo reason)
     at Mono.Linker.Steps.MarkStep.ProcessMarkedPending()
     at Mono.Linker.Steps.MarkStep.Initialize()
     at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
     at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
     at Mono.Linker.Pipeline.Process(LinkContext context)
     at Mono.Linker.Driver.Run(ILogger customLogger)
     at Mono.Linker.Driver.Main(String[] args)
  Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
/usr/local/share/dotnet/sdk/6.0.100-rc.1.21458.32/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ILLink.targets(108,5): error NETSDK1144: Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false. [/Users/lluis/prog/work/vsmac/test/main/src/tools/vstool/vstool.csproj]
```

The dotnet version is 6.0.100-rc.1.21458.32

### PR DESCRIPTION
**Pull request by tlakollo**
Do a null check for TryResolve(type.BaseType) before trying to get the attributes
Fix #2274

### CODE REVIEW

**Comment by marek-safar** [comment]
Please send email to tactics for approval

**Comment by tlakollo** [comment]
Got approval from tactics

**Comment by agocke** [comment]
Let's take this together with https://github.com/dotnet/linker/pull/2276 as they are both blocking critical scenarios

**Review by agocke — CHANGES_REQUESTED** [review]
This looks like only a partial fix. I think we should backport the whole thing. Picking out sections of a PR is likely more dangerous than taking the whole thing that was fully reviewed and tested.

**Comment by tlakollo** [comment]
I just tested all the changes and it breaks, apparently is necessary https://github.com/dotnet/linker/commit/397f69bdde14f0df2578a2f8e604213b3e831ca6
possibly even 
https://github.com/dotnet/linker/commit/39505a8e73d3ed4e6befa5b8bc7d32e2380c889a

**Review by agocke — APPROVED** [review]
LGTM

**Pull request merged**
